CFLAGS =-O2 -Wall --mno-cygwin
LDFLAGS=-L../ -luncl

PROGRAMS:=userver uclient
all: $(PROGRAMS)

userver: userver.c
	$(CC) $(CFLAGS) $< -o $@ $(LDFLAGS)

uclient: uclient.c
	$(CC) $(CFLAGS) $< -o $@ $(LDFLAGS)

clean:
	rm -f $(PROGRAMS) *.o tags *~
